name: Deploy NYC Mesh Status Page

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types:
      - completed

jobs:
  deploy_nyc_mesh_status_page:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MESH_STATUS_BOX_KEY }}
        name: id_ed25519 # optional
        known_hosts: ${{ secrets.MESH_STATUS_BOX_KNOWN_HOSTS }}
        #config: ${{ secrets.CONFIG }} # ssh_config; optional
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - name: Pull new Docker image
      run: ssh root@status.mesh.nycmesh.net "cd /root/cursed-status-page-live && bash update_and_restart.sh"
